# Generated by Django 3.2.12 on 2022-03-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('speciality', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('typeOfProvider', models.CharField(max_length=50)),
                ('dateOfBirth', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
    ]
